name: Update Bot Image
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests pillow
      - name: Run script
        run: python update_bot.py
        env:
          SVITLO_KEY: ${{ secrets.SVITLO_KEY }}
          SVITLO_KEY2: ${{ secrets.SVITLO_KEY2 }}
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git stash
          git pull --rebase
          git stash pop
          git add status.png
          git commit -m "Автоматичне оновлення інформера" || exit 0
          git push
